### ISSUE TITLE
How to get the googleaccesstoken?

### ISSUE THREAD

**Issue by rajanrawal** [awstudio-paris/Google-Photos-API#1]
Hi 

I want to use your package for one project where i need to fetch the all images for the specific album. Can you please add some notes in readme how to access it with some code sample?

I tried with google developer console and generated api key but it did not work. Can you please let me know how can we access it?

Thank you.

**Comment by awstudio-paris** [comment]
Hi,

I wrote some information about how to use the client. To access to the album you will need a Google Access Token, but right now we don't provide the way to get it. We recommend you to try to use a third party library that does OAuth2 logins, or maybe you can directly check the [google documentation](https://support.google.com/googleapi/answer/6158849) and try to do the calls manually. The scope that you will  have to set is `https://picasaweb.google.com/data/` . Sorry for the inconvenients, if you have some problem to get the token maybe we can help you.

Regards!

**Comment by awstudio-paris** [comment]
I'm closing the issue, if you have other issue feel free to open a new one.
